module.exports = {
	halo: "HALO JUGA* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	woi: "APA WOI* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	anjing: "KAU ANJING* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	babi: "KAU BABI* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	assalamualaikum: "WAALAIKUMUSSALAM* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	asalamualaikum: "WAALAIKUMUSSALAM* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	permisi: "IYA SILAHKAN* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	makasih: "SAMA SAMA* \n\njangan lupa untuk subscribe channel saya RIDHO SETIAWAN \r\n\r\n \n \r",
	terimakasih: "SAMA SAMA* \n\njangan lupa untuk subscribe channel saya RIDHO SETIAWAN \r\n\r\n \n \r",
	thanks: "SAMA SAMA* \n\njangan lupa untuk subscribe channel saya RIDHO SETIAWAN \r\n\r\n \n \r",
	thank: "SAMA SAMA* \n\njangan lupa untuk subscribe channel saya RIDHO SETIAWAN \r\n\r\n \n \r",
	hai: "HAI JUGAA!*\n\n ketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	ass: "WAALAIKUMSALAM*\n\n ketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	bro: "EUUUYYYY!!!* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	p: "pa bot*\n\n ketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	test: "*satu dua dicoba*\n\n ketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	sabar: "SABAR BOII LAGI DICARIIN",
	halo: "HALO JUGA* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	woi: "APA WOI* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	anjing: "KAU ANJING* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	babi: "KAU BABI* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	assalamualaikum: "WAALAIKUMUSSALAM* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	asalamualaikum: "WAALAIKUMUSSALAM* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	permisi: "IYA SILAHKAN* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	makasih: "SAMA SAMA* \n\njangan lupa untuk subscribe channel saya RIDHO SETIAWAN \r\n\r\n \n \r",
	terimakasih: "SAMA SAMA* \n\njangan lupa untuk subscribe channel saya RIDHO SETIAWAN \r\n\r\n \n \r",
	thanks: "SAMA SAMA* \n\njangan lupa untuk subscribe channel saya RIDHO SETIAWAN \r\n\r\n \n \r",
	thank: "SAMA SAMA* \n\njangan lupa untuk subscribe channel saya RIDHO SETIAWAN \r\n\r\n \n \r",
	hai: "HAI JUGAA!*\n\n ketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	ass: "WAALAIKUMSALAM*\n\n ketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	bro: "EUUUYYYY!!!* \n\nketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	p: "pa bot*\n\n ketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	test: "*satu dua dicoba*\n\n ketik *#help* untuk menampilkan semua fitur yang ada \r\n\r\n \n \r",
	sabar: "SABAR BOII LAGI DICARIIN",
}
